#! /usr/bin/env bash
#
## curl -L https://raw.githubusercontent.com/jmmk/archsalt/master/provision | bash

set -eo pipefail

log() {
  echo "bootstrap: $1"
}

check-exists() {
  which $1 > /dev/null
}

pkg-install() {
  sudo pacman -S $1 --noconfirm --needed
}

main() {
  log "Refresh package database"
  sudo pacman -Syyu --noconfirm

  log "Install git and reflector if not already installed"
  pkg-install git
  pkg-install reflector

  log "Run reflector to update mirrorlist"
  sudo reflector --country "United States" -l 30 -n 20 -p http --sort rate --save /etc/pacman.d/mirrorlist

  log "Run salt bootstrap if not installed"
  check-exists salt-call || curl -Ls https://bootstrap.saltstack.com | sudo sh

  log "Disable salt-minion service"
  sudo systemctl disable salt-minion.service

  log "Remove current salt directory and clone salt repo"
  sudo rm -rf /srv/salt
  sudo -E git clone -q --depth 1 https://github.com/jmmk/archsalt /srv/salt

  log "Run salt"
  sudo salt-call --local state.highstate -l info
}

main $@
