#! /usr/bin/env bash
set -eo pipefail

main() {
  curl -LO https://aur.archlinux.org/packages/st/st-git-zsh/st-git-zsh.tar.gz
  tar xvzf st-git-zsh.tar.gz
  cd st-git-zsh
  makepkg -sic --needed --noprogressbar --noconfirm
}

main "$@"
